version: '3'
services:
  webapp:
    build: webapp
    depends_on:
      - db-controller
    ports:
      - "8080:8080"
    volumes:
      - "./webapp:/code"
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: "gingerbreadman"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
       - "pgdata:/var/lib/postgresql/data"
  
  db-controller:
    build: db_controller
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./db_controller:/code"
  
  service_face_encoding:
    build: services/face_encoding
    depends_on:
      - db-controller
      - redis
    volumes:
      - "./services/face_encoding:/code"
  
  redis:
    image: redis
    volumes:
      - "redisdata:/data"

volumes:
  pgdata:
    driver: "local"

  redisdata:
    driver: local
