version: '3'
services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./:/code"

  service_face_analyzer:
    build:
      context: .
      dockerfile: Dockerfile_service_face_analyzer
    volumes:
      - "./:/code"
